sudo: required
languages: generic
services: 
  - docker
  
before_install:
  - docker build -t nikidenker/docker-react -f Dockerfile.dev .

script:
- docker run -e CI=true nikindenker/docker-react:latest npm run test
